import RASD_COMMON_LIBRARY as RASD_CL

def RASD(SETUP, OBJ):
    """
    THIS FUNCTION GENERATES RANDOM SAMPLES ACCORDING ,
    TO CHOICE SAMPLING METHOD
    
    INPUT:,
    SETUP: STOCHASTIC RANDOM VARIABLES DESCRIPTION (DICTIONARY MIXED)

    OUTPUT:
    RANDOM_SAMPLING: STOCHASTIC RANDOM SAMPLING (NP.ARRAY, FLOAT)
    """
    
    # CREATING SAMPLES   
    DATASET_X = RASD_CL.SAMPLING(SETUP)
    # N_SAMPLING
    N_SAMPLING = SETUP['TOTAL SAMPLING']
    N_G = SETUP['TOTAL DESIGN VARIABLES']
    # RESULTS
    RESULTS = np.zeros((N_SAMPLING, D + N_G))
    for I_COUNT in range(N_SAMPLING):
        SAMPLE = DATASET_X[I_COUNT, :]
        G = OBJ(SAMPLE)
        RESULTS = 


    return sampling_test